Added notifications
AEGEE/MyAEGEE pull request #37
Opened 2017-09-08 08:50 UTC by blacksph3re

Added new notification services and bumped core and serviceregistry versions to newest. Merge #35 first

2017-09-08 18:29 UTC, i3anaan commented
```bash ./oms.sh exec -T -d omsserviceregistry true 2>/dev/null || exit 1```
Failed here as well, same as #38

2017-09-20 17:29 UTC, i3anaan commented
Found the issue, the failing tests were a *legitimate* fail: The serviceregistry container was down. The test was working as intended.

See https://github.com/AEGEE/oms-docker/tree/add-notifications-derk

I 'fixed' the issue for Travis, ie. keeping the container running, however it is most definitely not truly fixed, as it is now spamming the log:

```
omsserviceregistry_1              | Could not register module with core, core replied with faulty response
omsserviceregistry_1              | ------------ Core response ----------
omsserviceregistry_1              | <!DOCTYPE html>
omsserviceregistry_1              | <html>
omsserviceregistry_1              |     <head>
omsserviceregistry_1              |         <meta charset="UTF-8" />
omsserviceregistry_1              |         <meta name="robots" content="noindex,nofollow" />
omsserviceregistry_1              |         <style>            body { background-color: #F9F9F9; color: #222; font: 14px/1.4 Helvetica, Arial, sans-serif; margin: 0; padding-bottom: 45px; }
omsserviceregistry_1              | 
omsserviceregistry_1              |             a { cursor: pointer; text-decoration: none; }
omsserviceregistry_1              |             a:hover { text-decoration: underline; }
omsserviceregistry_1              |             abbr[title] { border-bottom: none; cursor: help; text-decoration: none; }
omsserviceregistry_1              | 
omsserviceregistry_1              |             code, pre { font: 13px/1.5 Consolas, Monaco, Menlo, "Ubuntu Mono", "Liberation Mono", monospace; }
omsserviceregistry_1              | 
momsserviceregistry_1              |             table, tr, th, td { background: #FFF; border-collapse: collapse; vertical-align: top; }
omsserviceregistry_1              |             table { background: #FFF; border: 1px solid #E0E0E0; box-shadow: 0px 0px 1px rgba(128, 128, 128, .2); margin: 1em 0; width: 100%; }
omsserviceregistry_1              |             table th, table td { border: solid #E0E0E0; border-width: 1px 0; padding: 8px 10px; }
omsserviceregistry_1              |             table th { background-color: #E0E0E0; font-weight: bold; text-align: left; }
omsserviceregistry_1              | 
omsserviceregistry_1              |             .hidden-xs-down { display: none; }
omsserviceregistry_1              |             .block { display: block; }
omsserviceregistry_1              |             .break-long-words { -ms-word-break: break-all; word-break: break-all; word-break: break-word; -webkit-hyphens: auto; -moz-hyphens: auto; hyphens: auto; }
omsserviceregistry_1              |             .text-muted { color: #999; }
omsserviceregistry_1              | 
omsserviceregistry_1              |             .container { max-width: 1024px; margin: 0 auto; padding: 0 15px; }
omsserviceregistry_1              |             .container::after { content: ""; display: table; clear: both; }
omsserviceregistry_1              | 
omsserviceregistry_1              |             .exception-summary { background: #B0413E; border-bottom: 2px solid rgba(0, 0, 0, 0.1); border-top: 1px solid rgba(0, 0, 0, .3); flex: 0 0 auto; margin-bottom: 30px; }
omsserviceregistry_1              | 
omsserviceregistry_1              |             .exception-message-wrapper { display: flex; align-items: center; min-height: 70px; }
omsserviceregistry_1              |             .exception-message { flex-grow: 1; padding: 30px 0; }
omsserviceregistry_1              |             .exception-message, .exception-message a { color: #FFF; font-size: 21px; font-weight: 400; margin: 0; }
omsserviceregistry_1              |             .exception-message.long { font-size: 18px; }
omsserviceregistry_1              |             .exception-message a { text-decoration: none; }
omsserviceregistry_1              |             .exception-message a:hover { text-decoration: underline; }
omsserviceregistry_1              | 
omsserviceregistry_1              |             .exception-illustration { flex-basis: 111px; flex-shrink: 0; height: 66px; margin-left: 15px; opacity: .7; }
omsserviceregistry_1              | 
omsserviceregistry_1              |             .trace + .trace { margin-top: 30px; }
omsserviceregistry_1              |             .trace-head .trace-class { color: #222; font-size: 18px; font-weight: bold; line-height: 1.3; margin: 0; position: relative; }
omsserviceregistry_1              | 
omsserviceregistry_1              |             .trace-message { font-size: 14px; font-weight: normal; margin: .5em 0 0; }
omsserviceregistry_1              | 
omsserviceregistry_1              |             .trace-file-path, .trace-file-path a { margin-top: 3px; color: #999; color: #795da3; color: #B0413E; color: #222; font-size: 13px; }
omsserviceregistry_1              |             .trace-class { color: #B0413E; }
omsserviceregistry_1              |             .trace-type { padding: 0 2px; }
omsserviceregistry_1              |             .trace-method { color: #B0413E; color: #222; font-weight: bold; color: #B0413E; }
omsserviceregistry_1              |             .trace-arguments { color: #222; color: #999; font-weight: normal; color: #795da3; color: #777; padding-left: 2px; }
omsserviceregistry_1              | 
omsserviceregistry_1              |             @media (min-width: 575px) {
omsserviceregistry_1              |                 .hidden-xs-down { display: initial; }
omsserviceregistry_1              |             }</style>
omsserviceregistry_1              |     </head>
omsserviceregistry_1              |     <body>
omsserviceregistry_1              |                     <div class="exception-summary">
omsserviceregistry_1              |                 <div class="container">
omsserviceregistry_1              |                     <div class="exception-message-wrapper">
omsserviceregistry_1              |                         <h1 class="break-long-words exception-message">Whoops, looks like something went wrong.</h1>
omsserviceregistry_1              |                         <div class="exception-illustration hidden-xs-down"><svg viewBox="0 0 136 81" xmlns="http://www.w3.org/2000/svg" fill-rule="evenodd" clip-rule="evenodd" stroke-linejoin="round" stroke-miterlimit="1.414"><path d="M92.358 20.403a23.168 23.168 0 0 1 9.003 1.881 23.67 23.67 0 0 1 5.197 3.079 24.257 24.257 0 0 1 3.457 3.296 24.771 24.771 0 0 1 5.042 9.396c.486 1.72.78 3.492.895 5.28l.008.142.028.158.015.246v13.875c.116.034.232.065.348.098.193.054.383.116.577.168.487.125.989.191 1.49.215.338.016.689.023 1.021-.059.021-.005.032-.029.048-.044l.095-.1c.243-.265.461-.552.663-.851.277-.408.523-.837.746-1.279l.042-.087c-.066-.012-.131-.026-.197-.04l-.099-.023a5.536 5.536 0 0 1-.694-.242 5.649 5.649 0 0 1-2.374-1.845 5.694 5.694 0 0 1-.824-1.594 6.514 6.514 0 0 1-.267-2.781c.045-.394.126-.779.233-1.159.079-.278.162-.562.307-.812.094-.163.129-.196.247-.341l.79-.882c.143-.143.174-.186.34-.303.249-.174.536-.289.834-.333.074-.011.15-.014.224-.02l1.188-.037c.173.004.217-.002.388.028s.211.05.375.105l.018.007c.059.026.119.05.176.079.151.076.179.104.313.2l.006-.021c.073-.187.084-.238.187-.41.077-.129.167-.249.27-.357.051-.054.108-.103.162-.154l1.124-.95c.14-.107.172-.14.327-.224.155-.085.199-.094.363-.154l.019-.006c.169-.043.211-.06.385-.077.174-.016.218-.007.392.003l1.446.158c.193.033.244.033.43.098.278.097.534.259.744.47.053.053.1.112.149.167l.923 1.158.149.213.028.054.017-.014.184-.125c.196-.104.196-.104.402-.184l1.386-.451c.064-.018.126-.038.19-.052.129-.028.259-.042.39-.043.16-.002.321.017.478.047.364.069.711.21 1.032.396.162.094.316.199.469.308.088.063.176.132.27.188l.021.011c.19.123.245.146.409.305.185.178.336.393.443.63.035.079.061.162.091.243l.439 1.428c.045.175.062.219.081.4.02.193.006.381-.015.573a7.79 7.79 0 0 1-.101.645c-.09.455-.212.901-.365 1.339-.128.366-.273.73-.445 1.077-.658 1.335-1.652 2.512-2.917 3.265a6.399 6.399 0 0 1-1.019.489 6.097 6.097 0 0 1-.631.203c-.226.058-.455.1-.686.134l-.096.012-.061.007c-.01.176-.022.352-.036.528-.034.39 [...]

2017-09-20 17:31 UTC, i3anaan commented
Above error HTMLified:

![screenshot--2017-09-20-19-31-29-554](https://user-images.githubusercontent.com/2911348/30658229-574c2afc-9e3a-11e7-9559-1f27be590c4f.png)

2017-09-20 17:32 UTC, i3anaan requested changes
As noted in the comments, there is still a bug present

2018-07-03 19:25 UTC, linuxbandit commented
Me and Sergey are cleaning up the branches

2018-07-03 19:25 UTC, closed without merging