Mvp last tweaks (cleanup of structure)
AEGEE/MyAEGEE pull request #55
Opened 2018-07-05 09:34 UTC by linuxbandit

In theory this is the working backend without frontend yet. I am going to test it now, only the api should be successful anyway. Will add a reviewer when I finish testing

2018-07-05 10:31 UTC, serge1peshcoff requested changes

2018-07-05 10:31 UTC, serge1peshcoff commented on .env.example
> +PATH_OMS_LOGINSERVICE=oms-loginservice/docker/
do we need login service? since it's not used and it's in the core now

2018-07-05 10:31 UTC, serge1peshcoff commented on .gitmodules
> +[submodule "oms-loginservice"]
and here as well

2018-07-05 10:31 UTC, serge1peshcoff commented on .env.example
> +ENABLED_SERVICES=oms-global:oms-core:oms-serviceregistry:oms-events:oms-logo-print
did you mean `oms-core-elixir` instead of `oms-core`? :D

2018-07-05 10:32 UTC, linuxbandit commented on .env.example
> +PATH_OMS_LOGINSERVICE=oms-loginservice/docker/
i included it just to be sure but I agree with you

2018-07-05 10:32 UTC, linuxbandit commented on .env.example
> +ENABLED_SERVICES=oms-global:oms-core:oms-serviceregistry:oms-events:oms-logo-print
thanks! I will correct it

2018-07-08 15:04 UTC, serge1peshcoff approved these changes

2018-07-10 03:42 UTC, merged