Fix/edit readme
AEGEE/MyAEGEE pull request #745
Opened 2021-11-06 11:05 UTC by tiva7

Minor changes in the README.md file in order to improve the installation guide. Details: changed in order in installation and usage section; added url mapping common troubleshooting (win machine).

2021-11-06 11:21 UTC, WikiRik commented
Thanks for making your first GitHub pull request about MyAEGEE! We will take a look at your changes within a few days.

2021-11-07 13:13 UTC, WikiRik requested changes
Content wise it looks great, thanks for the cleanup and additions! I just have some small suggestions, if you commit these I think we're ready to merge this!

2021-11-07 13:13 UTC, WikiRik commented on README.md
> +## Advanced Url mapping and troubleshoot
```suggestion
## Advanced URL mapping and troubleshoot
```
Just makes it more in line with how it's called in line 69

2021-11-07 13:13 UTC, WikiRik commented on README.md
> +For any troubleshoot, see [advanced URL mapping and troubleshoot](#Advanced-Url-mapping-and-troubleshoot).
```suggestion
For any troubleshoot, see [Advanced URL mapping and troubleshoot](#advanced-url-mapping-and-troubleshoot).
```

2021-11-07 13:13 UTC, WikiRik commented on README.md
> +You will have to wait for up to 20'. A message appears when the bootstrap completes, and you can check if it works in the ways described in the [Usage section](#accessing-it).
```suggestion
You will have to wait for up to 20 minutes. A message appears when the bootstrap completes, and you can check if it works in the ways described in the [Usage section](#accessing-it).
```
Not your doing, but I think it might not be very clear for others

2021-11-07 13:13 UTC, WikiRik commented on README.md
> +You are encouraged to edit (a script will do it for you, read below) the `/etc/hosts` file on the _HOST_ machine (on windows: `C:\Windows\system32\drivers\etc\hosts`) to add the entry:
```suggestion
If the script above did not work, you can also manually edit the `/etc/hosts` file on the _HOST_ machine (on Windows: `C:\Windows\system32\drivers\etc\hosts`) to add the entry:
```

2021-11-07 13:13 UTC, WikiRik commented on README.md
> +**WINDOWS write-permission issue**
```suggestion
**Windows write-permission issue**
```

2021-11-07 13:13 UTC, WikiRik commented on README.md
> +For any issue, see [**Troubleshooting**](#Troubleshooting-/-other)
```suggestion
For any issue, see [**Troubleshooting**](#troubleshooting--other)
```

2021-11-07 13:13 UTC, WikiRik commented on README.md
> +For manual edits, see [advanced URL mapping and troubleshoot](#Advanced-Url-mapping-and-troubleshoot).
```suggestion
For manual edits, see [Advanced URL mapping and troubleshoot](#advanced-url-mapping-and-troubleshoot).
```

2021-11-07 13:13 UTC, WikiRik commented on README.md
> +See [below](#start.sh-and-Makefile) for explanation of `start.sh`
```suggestion
See [below](#startsh-and-makefile) for explanation of `start.sh`
```

2021-11-07 13:13 UTC, WikiRik commented on README.md
> +Explanation of the installation are here. Explanation of why we're doing it this way is [at the bottom](#Under-the-hood).
```suggestion
Explanation of the installation are here. Explanation of why we're doing it this way is [at the bottom](#under-the-hood).
```

2021-11-07 13:13 UTC, WikiRik commented on README.md
> +3.  B) (Docker case) Paste the content at the last line of the file
```suggestion
    B) (Docker case) Paste the content at the last line of the file 
```

2021-11-07 14:28 UTC, tiva7 reviewed
Thanks. Suggestions have been committed :)

2021-11-07 14:33 UTC, WikiRik approved these changes

2021-11-07 14:34 UTC, merged